wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: ShallowFBCSPNet
dataset:
  desc: null
  value: BNCI2014_001
epochs:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.45.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1739292602.0
    t:
      1:
      - 1
      - 5
      - 11
      - 32
      - 49
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 11
      - 32
      - 49
      - 53
      - 55
      - 77
      3:
      - 2
      - 16
      - 23
      4: 3.10.11
      5: 0.16.6
      6: 4.45.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
